### ISSUE TITLE
Error in Tutorial sheet 2, problem 8

### ISSUE THREAD

**Issue by maryam1506** [DE1-Engineering-Mathematics/module-resources#151]
I think there should be a comma in between the numbers in the vectors in this question.

![Screenshot 2021-10-23 at 17 13 04](https://user-images.githubusercontent.com/92755003/138563951-c2963e1f-b714-43fd-bbd7-501a1a3f4ed7.png)

**Comment by jackbeau** [comment]
Thanks for submitting this. Fixed!
