### ISSUE TITLE
Error in Tutorial Sheet 15, Problem 5, Part (b)

### ISSUE THREAD

**Issue by justinkeung1018** [DE1-Engineering-Mathematics/module-resources#165]
![image](https://user-images.githubusercontent.com/94550621/161793964-0c6c82cc-0db1-47b0-818b-9718859d8936.png)
The partial derivative wrt omega for (x, y) = (0.25, -0.3) in the first row should not be -3.2129. Opening the WolframAlpha link attached in the solution reveals that x = 0.5 was used instead of x = 0.25, resulting in the incorrect value for the derivative:
![image](https://user-images.githubusercontent.com/94550621/161794428-992fc840-da05-432e-ac95-116eb750cc3b.png)
I got 2.0339 for this derivative, which makes the first entry in the Jacobian vector to be 2.855 instead of 3.248.

Also in the table the partial derivative wrt omega for (x, y) = (1, 0.5) should be -6.02992 instead of 6.02992 (i.e. it's missing a negative sign).

**Comment by jackbeau** [comment]
Fixed! Thanks for reporting this
