### ISSUE TITLE
Would it be possible to get a imperial.ac.uk subdomain/url?

### ISSUE THREAD

**Issue by LegoYoda112** [DE1-Engineering-Mathematics/module-resources#69]
Its supported by GitHub. Presumably its technically possible from the college side? 

The real question is: Is the bureaucracy too much though?

https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by theobui** [comment]
I read up on the imperial policy, definitely not.
